volatile const char* isr_errors[32] = {
    "Division by zero",
    "Debug",
    "Non-maskable interrupt",
    "Breakpoint",
    "Detected overflow",
    "Out-of-bounds",
    "Invalid opcode",
    "No coprocessor",
    "Double fault",
    "Coprocessor segment overrun",
    "Bad TSS",
    "Segment not present",
    "Stack fault",
    "General protection fault",
    "Page fault",
    "Unknown interrupt",
    "Coprocessor fault",
    "Alignment check",
    "Machine check",
    "Reserved ISR ERR NO.19",
    "Reserved ISR ERR NO.20",
    "Reserved ISR ERR NO.21",
    "Reserved ISR ERR NO.22",
    "Reserved ISR ERR NO.23",
    "Reserved ISR ERR NO.24",
    "Reserved ISR ERR NO.25",
    "Reserved ISR ERR NO.26",
    "Reserved ISR ERR NO.27",
    "Reserved ISR ERR NO.28",
    "Reserved ISR ERR NO.29",
    "Reserved ISR ERR NO.30",
    "Reserved ISR ERR NO.31"
};
