#pragma once
#include "../rendering/BasicRenderer.h"
#include "../cStdLib/cstrTools.h"
#include "../rendering/Cols.h"
#include <stdint.h>
#include "../memory/heap.h"
#include "../paging/PageFrameAllocator.h"
#include "../userinput/keyboard.h"
#include "../userinput/mouse.h"
#include "../osData/osData.h"
#include "../devices/pit/pit.h"
#include "../tasks/sleep/taskSleep.h"
#include "../tasks/playBeep/playBeep.h"
#include "../tasks/test/testTask.h"
#include "../kernelStuff/diskStuff/Disk_Interfaces/ram/ramDiskInterface.h"
#include "../kernelStuff/diskStuff/Disk_Interfaces/file/fileDiskInterface.h"
#include "../kernelStuff/diskStuff/Partition_Interfaces/mraps/mrapsPartitionInterface.h"
#include "../kernelStuff/diskStuff/Filesystem_Interfaces/mrafs/mrafsFileSystemInterface.h"
#include "../WindowStuff/SubInstances/connect4Instance/connect4Instance.h"
#include "../tasks/taskMgrTask/taskMgrTask.h"
#include "../tasks/closeWindow/taskWindowClose.h"
#include "../tasks/bfTask/bfTask.h"
#include "../tasks/debugViewTask/debugViewTask.h"
#include "../fsStuff/fsStuff.h"
#include "../tasks/maab/maabTask.h"

int draw_cn(Window *win, char *str, uint32_t color);