include ../gdef.mk

PROGRAM_BUILD_DIR = ./bin

.PHONY: all
all: 
	@echo "Building all programs in $(BUILD_ARCH) architecture"
	@mkdir -p $(PROGRAM_BUILD_DIR)
	$(MAKE) -C desktop

	
	@echo "Copying programs to disk image..."
	e2mkdir ../$(PROGRAM_IMAGE_NAME).img:/bin/
	e2cp ./bin/desktop.elf ../$(PROGRAM_IMAGE_NAME).img:/bin/

clean:
	$(MAKE) -C desktop clean
	rm -rf $(PROGRAM_BUILD_DIR)